### ISSUE TITLE
Permanent users

### ISSUE THREAD

**Issue by sixfootseven** [n7tae/smart-group-server#5]
Is there a way this feature could be reinstated, perhaps with a function to check a user has transmitted through Quadnet in the previous 24hrs?

**Comment by n7tae** [comment]
Sorry, I can't support this. Clients don't send keep alive packets to the server, so the server doesn't know if a subscriber is still there. That's why there is a timeout in the first place. Smart Groups do send keep alive packets to subscribers (that's how a Smart Group stays connected over a smart-phone network). That's a potential waste of bandwidth to send a keep alive to a subscriber that's potentially not there.
